# Use lightweight Python 3.11
FROM python:3.11-slim

# working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Map project files into containers (hot update during development phase)
COPY . .

# FastAPI Hot overload startup
CMD ["uvicorn", "VAD.app:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
